version: '0'
services:
  fruitpal:
    container_name: fruitpal
    build: ./app
    volumes:
      - ./app:/app
      - ./data:/data # Copy directory with JSON data file to /data
    ports:
      - 8080:5000
    environment:
      - DEBUG=true
      - DATA_FILE=fruit_data.json
